general.import = [
	"~/.config/alacritty/themes/themes/coolnight.toml"
]

[env]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10

decorations = "Buttonless"

opacity = 1
blur = false

option_as_alt = "Both"

[font]
normal.family = "MesloLGS Nerd Font Mono"

size = 14

[scrolling]
history = 50000  # 50,000 lines of scrollback
